package com.example.timesheet.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Represents a timesheet entry for an employee, including the employee's name and hours worked.
 * This class is mapped to a database table using JPA annotations.
 */
@Entity // Marks this class as a JPA entity to be persisted in the database
public class Timesheet {

    /**
     * The unique identifier for the timesheet entry.
     * This value is automatically generated by the database.
     */
    @Id // Specifies the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generates the ID value
    private Long id;
    
    /**
     * The name of the employee associated with this timesheet entry.
     */
    private String employeeName;

    /**
     * The number of hours worked by the employee.
     */
    private int hoursWorked;

    /**
     * Gets the unique identifier for the timesheet entry.
     * @return the id of the timesheet
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier for the timesheet entry.
     * @param id the id to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name of the employee associated with this timesheet entry.
     * @return the employee's name
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * Sets the name of the employee associated with this timesheet entry.
     * @param employeeName the employee's name to set
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * Gets the number of hours worked by the employee.
     * @return the hours worked
     */
    public int getHoursWorked() {
        return hoursWorked;
    }

    /**
     * Sets the number of hours worked by the employee.
     * @param hoursWorked the hours worked to set
     */
    public void setHoursWorked(int hoursWorked) {
        this.hoursWorked = hoursWorked;
    }
}
